from typing import Dict, NamedTuple, Optional

from BaseClasses import Item, ItemClassification
from .Names import ItemName, LocationName

offset: int = 63900000
princess: int = 100
voice: int = 200
blade: int = 300
other: int = 400
memories: int = 10000


class SlayThePrincessItem(Item):
    game = "Slay The Princess"


class SlayThePrincessItemData(NamedTuple):
    code: Optional[int] = None
    type: ItemClassification = ItemClassification.filler


other_item_data_table: Dict[str, SlayThePrincessItemData] = {
    ItemName.filler: SlayThePrincessItemData(offset + 0, ItemClassification.filler),
    ItemName.mirror: SlayThePrincessItemData(offset + other + 1, ItemClassification.progression),
    ItemName.gift: SlayThePrincessItemData(offset + other + 2, ItemClassification.progression),
}

blade_item_data_table: Dict[str, SlayThePrincessItemData] = {
    ItemName.blade: SlayThePrincessItemData(offset + blade + 0, ItemClassification.progression),
}

blade_chapter_item_data_table: Dict[str, SlayThePrincessItemData] = {
    ItemName.blade1: SlayThePrincessItemData(offset + blade + 1, ItemClassification.progression),
    ItemName.blade2: SlayThePrincessItemData(offset + blade + 2, ItemClassification.progression),
    ItemName.blade3: SlayThePrincessItemData(offset + blade + 3, ItemClassification.progression),
    ItemName.blade4: SlayThePrincessItemData(offset + blade + 4, ItemClassification.progression),
}

blade_princess_item_data_table: Dict[str, SlayThePrincessItemData] = {
    ItemName.blade_princess: SlayThePrincessItemData(offset + blade + 5, ItemClassification.progression),
    ItemName.blade_adversary: SlayThePrincessItemData(offset + blade + 6, ItemClassification.progression),
    ItemName.blade_tower: SlayThePrincessItemData(offset + blade + 7, ItemClassification.progression),
    ItemName.blade_spectre: SlayThePrincessItemData(offset + blade + 8, ItemClassification.progression),
    ItemName.blade_nightmare: SlayThePrincessItemData(offset + blade + 9, ItemClassification.progression),
    ItemName.blade_razor: SlayThePrincessItemData(offset + blade + 10, ItemClassification.progression),
    ItemName.blade_beast: SlayThePrincessItemData(offset + blade + 11, ItemClassification.progression),
    ItemName.blade_witch: SlayThePrincessItemData(offset + blade + 12, ItemClassification.progression),
    ItemName.blade_stranger: SlayThePrincessItemData(offset + blade + 13, ItemClassification.progression),
    ItemName.blade_prisoner: SlayThePrincessItemData(offset + blade + 14, ItemClassification.progression),
    ItemName.blade_damsel: SlayThePrincessItemData(offset + blade + 15, ItemClassification.progression),
    ItemName.blade_needle: SlayThePrincessItemData(offset + blade + 16, ItemClassification.progression),
    ItemName.blade_fury: SlayThePrincessItemData(offset + blade + 17, ItemClassification.progression),
    ItemName.blade_apotheosis: SlayThePrincessItemData(offset + blade + 18, ItemClassification.progression),
    ItemName.blade_dragon: SlayThePrincessItemData(offset + blade + 19, ItemClassification.progression),
    ItemName.blade_den: SlayThePrincessItemData(offset + blade + 20, ItemClassification.progression),
    ItemName.blade_clarity: SlayThePrincessItemData(offset + blade + 21, ItemClassification.progression),
    ItemName.blade_wild: SlayThePrincessItemData(offset + blade + 22, ItemClassification.progression),
    ItemName.blade_thorn: SlayThePrincessItemData(offset + blade + 23, ItemClassification.progression),
    ItemName.blade_cage: SlayThePrincessItemData(offset + blade + 24, ItemClassification.progression),
    ItemName.blade_grey: SlayThePrincessItemData(offset + blade + 25, ItemClassification.progression),
    ItemName.blade_happily: SlayThePrincessItemData(offset + blade + 26, ItemClassification.progression),
    ItemName.blade_goddess: SlayThePrincessItemData(offset + blade + 27, ItemClassification.progression),
}

princess_item_data_table: Dict[str, SlayThePrincessItemData] = {
    ItemName.adversary: SlayThePrincessItemData(offset + princess + 0, ItemClassification.progression),
    ItemName.tower: SlayThePrincessItemData(offset + princess + 1, ItemClassification.progression),
    ItemName.spectre: SlayThePrincessItemData(offset + princess + 2, ItemClassification.progression),
    ItemName.nightmare: SlayThePrincessItemData(offset + princess + 3, ItemClassification.progression),
    ItemName.razor: SlayThePrincessItemData(offset + princess + 4, ItemClassification.progression),
    ItemName.beast: SlayThePrincessItemData(offset + princess + 5, ItemClassification.progression),
    ItemName.witch: SlayThePrincessItemData(offset + princess + 6, ItemClassification.progression),
    ItemName.stranger: SlayThePrincessItemData(offset + princess + 7, ItemClassification.progression),
    ItemName.prisoner: SlayThePrincessItemData(offset + princess + 8, ItemClassification.progression),
    ItemName.damsel: SlayThePrincessItemData(offset + princess + 9, ItemClassification.progression),

    ItemName.needle: SlayThePrincessItemData(offset + princess + 10, ItemClassification.progression),
    ItemName.fury: SlayThePrincessItemData(offset + princess + 11, ItemClassification.progression),
    ItemName.apotheosis: SlayThePrincessItemData(offset + princess + 12, ItemClassification.progression),
    ItemName.dragon: SlayThePrincessItemData(offset + princess + 13, ItemClassification.progression),
    ItemName.wraith: SlayThePrincessItemData(offset + princess + 14, ItemClassification.progression),
    ItemName.clarity: SlayThePrincessItemData(offset + princess + 15, ItemClassification.progression),
    ItemName.den: SlayThePrincessItemData(offset + princess + 16, ItemClassification.progression),
    ItemName.wild: SlayThePrincessItemData(offset + princess + 17, ItemClassification.progression),
    ItemName.thorn: SlayThePrincessItemData(offset + princess + 18, ItemClassification.progression),
    ItemName.cage: SlayThePrincessItemData(offset + princess + 19, ItemClassification.progression),
    ItemName.grey: SlayThePrincessItemData(offset + princess + 20, ItemClassification.progression),
    ItemName.happily: SlayThePrincessItemData(offset + princess + 21, ItemClassification.progression),

    ItemName.goddess: SlayThePrincessItemData(offset + princess + 22, ItemClassification.progression)
}

voice_item_data_table: Dict[str, SlayThePrincessItemData] = {
    ItemName.broken: SlayThePrincessItemData(offset + voice + 0, ItemClassification.progression),
    ItemName.cheated: SlayThePrincessItemData(offset + voice + 1, ItemClassification.progression),
    ItemName.cold: SlayThePrincessItemData(offset + voice + 2, ItemClassification.progression),
    ItemName.contrarian: SlayThePrincessItemData(offset + voice + 3, ItemClassification.progression),
    ItemName.hunted: SlayThePrincessItemData(offset + voice + 4, ItemClassification.progression),
    ItemName.opportunist: SlayThePrincessItemData(offset + voice + 5, ItemClassification.progression),
    ItemName.paranoid: SlayThePrincessItemData(offset + voice + 6, ItemClassification.progression),
    ItemName.skeptic: SlayThePrincessItemData(offset + voice + 7, ItemClassification.progression),
    ItemName.smitten: SlayThePrincessItemData(offset + voice + 8, ItemClassification.progression),
    ItemName.stubborn: SlayThePrincessItemData(offset + voice + 9, ItemClassification.progression),
}

gallery_item_data_table: Dict[str, SlayThePrincessItemData] = {
    LocationName.gallery_princess[1]: SlayThePrincessItemData(offset + memories + 1, ItemClassification.filler),
    LocationName.gallery_princess[2]: SlayThePrincessItemData(offset + memories + 2, ItemClassification.filler),
    LocationName.gallery_princess[3]: SlayThePrincessItemData(offset + memories + 3, ItemClassification.filler),
    LocationName.gallery_princess[4]: SlayThePrincessItemData(offset + memories + 4, ItemClassification.filler),
    LocationName.gallery_princess[5]: SlayThePrincessItemData(offset + memories + 5, ItemClassification.filler),
    LocationName.gallery_princess[6]: SlayThePrincessItemData(offset + memories + 6, ItemClassification.filler),
    LocationName.gallery_princess[7]: SlayThePrincessItemData(offset + memories + 7, ItemClassification.filler),
    LocationName.gallery_princess[8]: SlayThePrincessItemData(offset + memories + 8, ItemClassification.filler),
    LocationName.gallery_princess[9]: SlayThePrincessItemData(offset + memories + 9, ItemClassification.filler),
    LocationName.gallery_princess[10]: SlayThePrincessItemData(offset + memories + 10, ItemClassification.filler),
    LocationName.gallery_princess[11]: SlayThePrincessItemData(offset + memories + 11, ItemClassification.filler),
    LocationName.gallery_princess[12]: SlayThePrincessItemData(offset + memories + 12, ItemClassification.filler),
    LocationName.gallery_princess[13]: SlayThePrincessItemData(offset + memories + 13, ItemClassification.filler),
    LocationName.gallery_princess[14]: SlayThePrincessItemData(offset + memories + 14, ItemClassification.filler),
    LocationName.gallery_princess[15]: SlayThePrincessItemData(offset + memories + 15, ItemClassification.filler),
    LocationName.gallery_princess[16]: SlayThePrincessItemData(offset + memories + 16, ItemClassification.filler),
    LocationName.gallery_princess[17]: SlayThePrincessItemData(offset + memories + 17, ItemClassification.filler),
    LocationName.gallery_princess[18]: SlayThePrincessItemData(offset + memories + 18, ItemClassification.filler),

    LocationName.gallery_spaceBetween[1]: SlayThePrincessItemData(offset + memories + 101, ItemClassification.filler),
    LocationName.gallery_spaceBetween[2]: SlayThePrincessItemData(offset + memories + 102, ItemClassification.filler),
    LocationName.gallery_spaceBetween[3]: SlayThePrincessItemData(offset + memories + 103, ItemClassification.filler),
    LocationName.gallery_spaceBetween[4]: SlayThePrincessItemData(offset + memories + 104, ItemClassification.filler),
    LocationName.gallery_spaceBetween[5]: SlayThePrincessItemData(offset + memories + 105, ItemClassification.filler),
    LocationName.gallery_spaceBetween[6]: SlayThePrincessItemData(offset + memories + 106, ItemClassification.filler),
    LocationName.gallery_spaceBetween[7]: SlayThePrincessItemData(offset + memories + 107, ItemClassification.filler),
    LocationName.gallery_spaceBetween[8]: SlayThePrincessItemData(offset + memories + 108, ItemClassification.filler),
    LocationName.gallery_spaceBetween[9]: SlayThePrincessItemData(offset + memories + 109, ItemClassification.filler),

    LocationName.gallery_finale[1]: SlayThePrincessItemData(offset + memories + 201, ItemClassification.filler),
    LocationName.gallery_finale[2]: SlayThePrincessItemData(offset + memories + 202, ItemClassification.filler),
    LocationName.gallery_finale[3]: SlayThePrincessItemData(offset + memories + 203, ItemClassification.filler),
    LocationName.gallery_finale[4]: SlayThePrincessItemData(offset + memories + 204, ItemClassification.filler),
    LocationName.gallery_finale[5]: SlayThePrincessItemData(offset + memories + 205, ItemClassification.filler),
    LocationName.gallery_finale[6]: SlayThePrincessItemData(offset + memories + 206, ItemClassification.filler),
    LocationName.gallery_finale[7]: SlayThePrincessItemData(offset + memories + 207, ItemClassification.filler),
    LocationName.gallery_finale[8]: SlayThePrincessItemData(offset + memories + 208, ItemClassification.filler),
    LocationName.gallery_finale[9]: SlayThePrincessItemData(offset + memories + 209, ItemClassification.filler),
    LocationName.gallery_finale[10]: SlayThePrincessItemData(offset + memories + 210, ItemClassification.filler),
    LocationName.gallery_finale[11]: SlayThePrincessItemData(offset + memories + 211, ItemClassification.filler),
    LocationName.gallery_finale[12]: SlayThePrincessItemData(offset + memories + 212, ItemClassification.filler),
    LocationName.gallery_finale[13]: SlayThePrincessItemData(offset + memories + 213, ItemClassification.filler),
    LocationName.gallery_finale[14]: SlayThePrincessItemData(offset + memories + 214, ItemClassification.filler),
    LocationName.gallery_finale[15]: SlayThePrincessItemData(offset + memories + 215, ItemClassification.filler),
    LocationName.gallery_finale[16]: SlayThePrincessItemData(offset + memories + 216, ItemClassification.filler),
    LocationName.gallery_finale[17]: SlayThePrincessItemData(offset + memories + 217, ItemClassification.filler),
    LocationName.gallery_finale[18]: SlayThePrincessItemData(offset + memories + 218, ItemClassification.filler),
    LocationName.gallery_finale[19]: SlayThePrincessItemData(offset + memories + 219, ItemClassification.filler),
    LocationName.gallery_finale[20]: SlayThePrincessItemData(offset + memories + 220, ItemClassification.filler),

    LocationName.gallery_adversary[1]: SlayThePrincessItemData(offset + memories + 301, ItemClassification.filler),
    LocationName.gallery_adversary[2]: SlayThePrincessItemData(offset + memories + 302, ItemClassification.filler),
    LocationName.gallery_adversary[3]: SlayThePrincessItemData(offset + memories + 303, ItemClassification.filler),
    LocationName.gallery_adversary[4]: SlayThePrincessItemData(offset + memories + 304, ItemClassification.filler),
    LocationName.gallery_adversary[5]: SlayThePrincessItemData(offset + memories + 305, ItemClassification.filler),
    LocationName.gallery_adversary[6]: SlayThePrincessItemData(offset + memories + 306, ItemClassification.filler),
    LocationName.gallery_adversary[7]: SlayThePrincessItemData(offset + memories + 307, ItemClassification.filler),
    LocationName.gallery_adversary[8]: SlayThePrincessItemData(offset + memories + 308, ItemClassification.filler),
    LocationName.gallery_adversary[9]: SlayThePrincessItemData(offset + memories + 309, ItemClassification.filler),
    LocationName.gallery_adversary[10]: SlayThePrincessItemData(offset + memories + 310, ItemClassification.filler),
    LocationName.gallery_adversary[11]: SlayThePrincessItemData(offset + memories + 311, ItemClassification.filler),
    LocationName.gallery_adversary[12]: SlayThePrincessItemData(offset + memories + 312, ItemClassification.filler),
    LocationName.gallery_adversary[13]: SlayThePrincessItemData(offset + memories + 313, ItemClassification.filler),
    LocationName.gallery_adversary[14]: SlayThePrincessItemData(offset + memories + 314, ItemClassification.filler),
    LocationName.gallery_adversary[15]: SlayThePrincessItemData(offset + memories + 315, ItemClassification.filler),
    LocationName.gallery_adversary[16]: SlayThePrincessItemData(offset + memories + 316, ItemClassification.filler),
    LocationName.gallery_adversary[17]: SlayThePrincessItemData(offset + memories + 317, ItemClassification.filler),
    LocationName.gallery_adversary[18]: SlayThePrincessItemData(offset + memories + 318, ItemClassification.filler),
    LocationName.gallery_adversary[19]: SlayThePrincessItemData(offset + memories + 319, ItemClassification.filler),
    LocationName.gallery_adversary[20]: SlayThePrincessItemData(offset + memories + 320, ItemClassification.filler),

    LocationName.gallery_tower[1]: SlayThePrincessItemData(offset + memories + 401, ItemClassification.filler),
    LocationName.gallery_tower[2]: SlayThePrincessItemData(offset + memories + 402, ItemClassification.filler),
    LocationName.gallery_tower[3]: SlayThePrincessItemData(offset + memories + 403, ItemClassification.filler),
    LocationName.gallery_tower[4]: SlayThePrincessItemData(offset + memories + 404, ItemClassification.filler),
    LocationName.gallery_tower[5]: SlayThePrincessItemData(offset + memories + 405, ItemClassification.filler),
    LocationName.gallery_tower[6]: SlayThePrincessItemData(offset + memories + 406, ItemClassification.filler),
    LocationName.gallery_tower[7]: SlayThePrincessItemData(offset + memories + 407, ItemClassification.filler),
    LocationName.gallery_tower[8]: SlayThePrincessItemData(offset + memories + 408, ItemClassification.filler),
    LocationName.gallery_tower[9]: SlayThePrincessItemData(offset + memories + 409, ItemClassification.filler),
    LocationName.gallery_tower[10]: SlayThePrincessItemData(offset + memories + 410, ItemClassification.filler),
    LocationName.gallery_tower[11]: SlayThePrincessItemData(offset + memories + 411, ItemClassification.filler),
    LocationName.gallery_tower[12]: SlayThePrincessItemData(offset + memories + 412, ItemClassification.filler),
    LocationName.gallery_tower[13]: SlayThePrincessItemData(offset + memories + 413, ItemClassification.filler),

    LocationName.gallery_spectre[1]: SlayThePrincessItemData(offset + memories + 501, ItemClassification.filler),
    LocationName.gallery_spectre[2]: SlayThePrincessItemData(offset + memories + 502, ItemClassification.filler),
    LocationName.gallery_spectre[3]: SlayThePrincessItemData(offset + memories + 503, ItemClassification.filler),
    LocationName.gallery_spectre[4]: SlayThePrincessItemData(offset + memories + 504, ItemClassification.filler),
    LocationName.gallery_spectre[5]: SlayThePrincessItemData(offset + memories + 505, ItemClassification.filler),
    LocationName.gallery_spectre[6]: SlayThePrincessItemData(offset + memories + 506, ItemClassification.filler),
    LocationName.gallery_spectre[7]: SlayThePrincessItemData(offset + memories + 507, ItemClassification.filler),
    LocationName.gallery_spectre[8]: SlayThePrincessItemData(offset + memories + 508, ItemClassification.filler),
    LocationName.gallery_spectre[9]: SlayThePrincessItemData(offset + memories + 509, ItemClassification.filler),
    LocationName.gallery_spectre[10]: SlayThePrincessItemData(offset + memories + 510, ItemClassification.filler),
    LocationName.gallery_spectre[11]: SlayThePrincessItemData(offset + memories + 511, ItemClassification.filler),
    LocationName.gallery_spectre[12]: SlayThePrincessItemData(offset + memories + 512, ItemClassification.filler),
    LocationName.gallery_spectre[13]: SlayThePrincessItemData(offset + memories + 513, ItemClassification.filler),
    LocationName.gallery_spectre[14]: SlayThePrincessItemData(offset + memories + 514, ItemClassification.filler),
    LocationName.gallery_spectre[15]: SlayThePrincessItemData(offset + memories + 515, ItemClassification.filler),
    LocationName.gallery_spectre[16]: SlayThePrincessItemData(offset + memories + 516, ItemClassification.filler),
    LocationName.gallery_spectre[17]: SlayThePrincessItemData(offset + memories + 517, ItemClassification.filler),
    LocationName.gallery_spectre[18]: SlayThePrincessItemData(offset + memories + 518, ItemClassification.filler),

    LocationName.gallery_nightmare[1]: SlayThePrincessItemData(offset + memories + 601, ItemClassification.filler),
    LocationName.gallery_nightmare[2]: SlayThePrincessItemData(offset + memories + 602, ItemClassification.filler),
    LocationName.gallery_nightmare[3]: SlayThePrincessItemData(offset + memories + 603, ItemClassification.filler),
    LocationName.gallery_nightmare[4]: SlayThePrincessItemData(offset + memories + 604, ItemClassification.filler),
    LocationName.gallery_nightmare[5]: SlayThePrincessItemData(offset + memories + 605, ItemClassification.filler),
    LocationName.gallery_nightmare[6]: SlayThePrincessItemData(offset + memories + 606, ItemClassification.filler),
    LocationName.gallery_nightmare[7]: SlayThePrincessItemData(offset + memories + 607, ItemClassification.filler),
    LocationName.gallery_nightmare[8]: SlayThePrincessItemData(offset + memories + 608, ItemClassification.filler),
    LocationName.gallery_nightmare[9]: SlayThePrincessItemData(offset + memories + 609, ItemClassification.filler),
    LocationName.gallery_nightmare[10]: SlayThePrincessItemData(offset + memories + 610, ItemClassification.filler),
    LocationName.gallery_nightmare[11]: SlayThePrincessItemData(offset + memories + 611, ItemClassification.filler),
    LocationName.gallery_nightmare[12]: SlayThePrincessItemData(offset + memories + 612, ItemClassification.filler),
    LocationName.gallery_nightmare[13]: SlayThePrincessItemData(offset + memories + 613, ItemClassification.filler),
    LocationName.gallery_nightmare[14]: SlayThePrincessItemData(offset + memories + 614, ItemClassification.filler),
    LocationName.gallery_nightmare[15]: SlayThePrincessItemData(offset + memories + 615, ItemClassification.filler),
    LocationName.gallery_nightmare[16]: SlayThePrincessItemData(offset + memories + 616, ItemClassification.filler),
    LocationName.gallery_nightmare[17]: SlayThePrincessItemData(offset + memories + 617, ItemClassification.filler),
    LocationName.gallery_nightmare[18]: SlayThePrincessItemData(offset + memories + 618, ItemClassification.filler),
    LocationName.gallery_nightmare[19]: SlayThePrincessItemData(offset + memories + 619, ItemClassification.filler),

    LocationName.gallery_razor[1]: SlayThePrincessItemData(offset + memories + 701, ItemClassification.filler),
    LocationName.gallery_razor[2]: SlayThePrincessItemData(offset + memories + 702, ItemClassification.filler),
    LocationName.gallery_razor[3]: SlayThePrincessItemData(offset + memories + 703, ItemClassification.filler),
    LocationName.gallery_razor[4]: SlayThePrincessItemData(offset + memories + 704, ItemClassification.filler),
    LocationName.gallery_razor[5]: SlayThePrincessItemData(offset + memories + 705, ItemClassification.filler),
    LocationName.gallery_razor[6]: SlayThePrincessItemData(offset + memories + 706, ItemClassification.filler),
    LocationName.gallery_razor[7]: SlayThePrincessItemData(offset + memories + 707, ItemClassification.filler),
    LocationName.gallery_razor[8]: SlayThePrincessItemData(offset + memories + 708, ItemClassification.filler),
    LocationName.gallery_razor[9]: SlayThePrincessItemData(offset + memories + 709, ItemClassification.filler),
    LocationName.gallery_razor[10]: SlayThePrincessItemData(offset + memories + 710, ItemClassification.filler),
    LocationName.gallery_razor[11]: SlayThePrincessItemData(offset + memories + 711, ItemClassification.filler),
    LocationName.gallery_razor[12]: SlayThePrincessItemData(offset + memories + 712, ItemClassification.filler),
    LocationName.gallery_razor[13]: SlayThePrincessItemData(offset + memories + 713, ItemClassification.filler),
    LocationName.gallery_razor[14]: SlayThePrincessItemData(offset + memories + 714, ItemClassification.filler),
    LocationName.gallery_razor[15]: SlayThePrincessItemData(offset + memories + 715, ItemClassification.filler),
    LocationName.gallery_razor[16]: SlayThePrincessItemData(offset + memories + 716, ItemClassification.filler),
    LocationName.gallery_razor[17]: SlayThePrincessItemData(offset + memories + 717, ItemClassification.filler),
    LocationName.gallery_razor[18]: SlayThePrincessItemData(offset + memories + 718, ItemClassification.filler),
    LocationName.gallery_razor[19]: SlayThePrincessItemData(offset + memories + 719, ItemClassification.filler),
    LocationName.gallery_razor[20]: SlayThePrincessItemData(offset + memories + 720, ItemClassification.filler),

    LocationName.gallery_beast[1]: SlayThePrincessItemData(offset + memories + 801, ItemClassification.filler),
    LocationName.gallery_beast[2]: SlayThePrincessItemData(offset + memories + 802, ItemClassification.filler),
    LocationName.gallery_beast[3]: SlayThePrincessItemData(offset + memories + 803, ItemClassification.filler),
    LocationName.gallery_beast[4]: SlayThePrincessItemData(offset + memories + 804, ItemClassification.filler),
    LocationName.gallery_beast[5]: SlayThePrincessItemData(offset + memories + 805, ItemClassification.filler),
    LocationName.gallery_beast[6]: SlayThePrincessItemData(offset + memories + 806, ItemClassification.filler),
    LocationName.gallery_beast[7]: SlayThePrincessItemData(offset + memories + 807, ItemClassification.filler),
    LocationName.gallery_beast[8]: SlayThePrincessItemData(offset + memories + 808, ItemClassification.filler),
    LocationName.gallery_beast[9]: SlayThePrincessItemData(offset + memories + 809, ItemClassification.filler),
    LocationName.gallery_beast[10]: SlayThePrincessItemData(offset + memories + 810, ItemClassification.filler),
    LocationName.gallery_beast[11]: SlayThePrincessItemData(offset + memories + 811, ItemClassification.filler),
    LocationName.gallery_beast[12]: SlayThePrincessItemData(offset + memories + 812, ItemClassification.filler),
    LocationName.gallery_beast[13]: SlayThePrincessItemData(offset + memories + 813, ItemClassification.filler),
    LocationName.gallery_beast[14]: SlayThePrincessItemData(offset + memories + 814, ItemClassification.filler),
    LocationName.gallery_beast[15]: SlayThePrincessItemData(offset + memories + 815, ItemClassification.filler),
    LocationName.gallery_beast[16]: SlayThePrincessItemData(offset + memories + 816, ItemClassification.filler),
    LocationName.gallery_beast[17]: SlayThePrincessItemData(offset + memories + 817, ItemClassification.filler),

    LocationName.gallery_witch[1]: SlayThePrincessItemData(offset + memories + 901, ItemClassification.filler),
    LocationName.gallery_witch[2]: SlayThePrincessItemData(offset + memories + 902, ItemClassification.filler),
    LocationName.gallery_witch[3]: SlayThePrincessItemData(offset + memories + 903, ItemClassification.filler),
    LocationName.gallery_witch[4]: SlayThePrincessItemData(offset + memories + 904, ItemClassification.filler),
    LocationName.gallery_witch[5]: SlayThePrincessItemData(offset + memories + 905, ItemClassification.filler),
    LocationName.gallery_witch[6]: SlayThePrincessItemData(offset + memories + 906, ItemClassification.filler),
    LocationName.gallery_witch[7]: SlayThePrincessItemData(offset + memories + 907, ItemClassification.filler),
    LocationName.gallery_witch[8]: SlayThePrincessItemData(offset + memories + 908, ItemClassification.filler),
    LocationName.gallery_witch[9]: SlayThePrincessItemData(offset + memories + 909, ItemClassification.filler),
    LocationName.gallery_witch[10]: SlayThePrincessItemData(offset + memories + 910, ItemClassification.filler),
    LocationName.gallery_witch[11]: SlayThePrincessItemData(offset + memories + 911, ItemClassification.filler),
    LocationName.gallery_witch[12]: SlayThePrincessItemData(offset + memories + 912, ItemClassification.filler),
    LocationName.gallery_witch[13]: SlayThePrincessItemData(offset + memories + 913, ItemClassification.filler),
    LocationName.gallery_witch[14]: SlayThePrincessItemData(offset + memories + 914, ItemClassification.filler),
    LocationName.gallery_witch[15]: SlayThePrincessItemData(offset + memories + 915, ItemClassification.filler),
    LocationName.gallery_witch[16]: SlayThePrincessItemData(offset + memories + 916, ItemClassification.filler),
    LocationName.gallery_witch[17]: SlayThePrincessItemData(offset + memories + 917, ItemClassification.filler),
    LocationName.gallery_witch[18]: SlayThePrincessItemData(offset + memories + 918, ItemClassification.filler),
    LocationName.gallery_witch[19]: SlayThePrincessItemData(offset + memories + 919, ItemClassification.filler),
    LocationName.gallery_witch[20]: SlayThePrincessItemData(offset + memories + 920, ItemClassification.filler),

    LocationName.gallery_stranger[1]: SlayThePrincessItemData(offset + memories + 1001, ItemClassification.filler),
    LocationName.gallery_stranger[2]: SlayThePrincessItemData(offset + memories + 1002, ItemClassification.filler),
    LocationName.gallery_stranger[3]: SlayThePrincessItemData(offset + memories + 1003, ItemClassification.filler),
    LocationName.gallery_stranger[4]: SlayThePrincessItemData(offset + memories + 1004, ItemClassification.filler),
    LocationName.gallery_stranger[5]: SlayThePrincessItemData(offset + memories + 1005, ItemClassification.filler),
    LocationName.gallery_stranger[6]: SlayThePrincessItemData(offset + memories + 1006, ItemClassification.filler),
    LocationName.gallery_stranger[7]: SlayThePrincessItemData(offset + memories + 1007, ItemClassification.filler),
    LocationName.gallery_stranger[8]: SlayThePrincessItemData(offset + memories + 1008, ItemClassification.filler),
    LocationName.gallery_stranger[9]: SlayThePrincessItemData(offset + memories + 1009, ItemClassification.filler),
    LocationName.gallery_stranger[10]: SlayThePrincessItemData(offset + memories + 1010, ItemClassification.filler),
    LocationName.gallery_stranger[11]: SlayThePrincessItemData(offset + memories + 1011, ItemClassification.filler),
    LocationName.gallery_stranger[12]: SlayThePrincessItemData(offset + memories + 1012, ItemClassification.filler),

    LocationName.gallery_prisoner[1]: SlayThePrincessItemData(offset + memories + 1101, ItemClassification.filler),
    LocationName.gallery_prisoner[2]: SlayThePrincessItemData(offset + memories + 1102, ItemClassification.filler),
    LocationName.gallery_prisoner[3]: SlayThePrincessItemData(offset + memories + 1103, ItemClassification.filler),
    LocationName.gallery_prisoner[4]: SlayThePrincessItemData(offset + memories + 1104, ItemClassification.filler),
    LocationName.gallery_prisoner[5]: SlayThePrincessItemData(offset + memories + 1105, ItemClassification.filler),
    LocationName.gallery_prisoner[6]: SlayThePrincessItemData(offset + memories + 1106, ItemClassification.filler),
    LocationName.gallery_prisoner[7]: SlayThePrincessItemData(offset + memories + 1107, ItemClassification.filler),
    LocationName.gallery_prisoner[8]: SlayThePrincessItemData(offset + memories + 1108, ItemClassification.filler),
    LocationName.gallery_prisoner[9]: SlayThePrincessItemData(offset + memories + 1109, ItemClassification.filler),
    LocationName.gallery_prisoner[10]: SlayThePrincessItemData(offset + memories + 1110, ItemClassification.filler),
    LocationName.gallery_prisoner[11]: SlayThePrincessItemData(offset + memories + 1111, ItemClassification.filler),
    LocationName.gallery_prisoner[12]: SlayThePrincessItemData(offset + memories + 1112, ItemClassification.filler),
    LocationName.gallery_prisoner[13]: SlayThePrincessItemData(offset + memories + 1113, ItemClassification.filler),
    LocationName.gallery_prisoner[14]: SlayThePrincessItemData(offset + memories + 1114, ItemClassification.filler),
    LocationName.gallery_prisoner[15]: SlayThePrincessItemData(offset + memories + 1115, ItemClassification.filler),
    LocationName.gallery_prisoner[16]: SlayThePrincessItemData(offset + memories + 1116, ItemClassification.filler),
    LocationName.gallery_prisoner[17]: SlayThePrincessItemData(offset + memories + 1117, ItemClassification.filler),

    LocationName.gallery_damsel[1]: SlayThePrincessItemData(offset + memories + 1201, ItemClassification.filler),
    LocationName.gallery_damsel[2]: SlayThePrincessItemData(offset + memories + 1202, ItemClassification.filler),
    LocationName.gallery_damsel[3]: SlayThePrincessItemData(offset + memories + 1203, ItemClassification.filler),
    LocationName.gallery_damsel[4]: SlayThePrincessItemData(offset + memories + 1204, ItemClassification.filler),
    LocationName.gallery_damsel[5]: SlayThePrincessItemData(offset + memories + 1205, ItemClassification.filler),
    LocationName.gallery_damsel[6]: SlayThePrincessItemData(offset + memories + 1206, ItemClassification.filler),
    LocationName.gallery_damsel[7]: SlayThePrincessItemData(offset + memories + 1207, ItemClassification.filler),
    LocationName.gallery_damsel[8]: SlayThePrincessItemData(offset + memories + 1208, ItemClassification.filler),
    LocationName.gallery_damsel[9]: SlayThePrincessItemData(offset + memories + 1209, ItemClassification.filler),
    LocationName.gallery_damsel[10]: SlayThePrincessItemData(offset + memories + 1210, ItemClassification.filler),
    LocationName.gallery_damsel[11]: SlayThePrincessItemData(offset + memories + 1211, ItemClassification.filler),
    LocationName.gallery_damsel[12]: SlayThePrincessItemData(offset + memories + 1212, ItemClassification.filler),
    LocationName.gallery_damsel[13]: SlayThePrincessItemData(offset + memories + 1213, ItemClassification.filler),
    LocationName.gallery_damsel[14]: SlayThePrincessItemData(offset + memories + 1214, ItemClassification.filler),
    LocationName.gallery_damsel[15]: SlayThePrincessItemData(offset + memories + 1215, ItemClassification.filler),
    LocationName.gallery_damsel[16]: SlayThePrincessItemData(offset + memories + 1216, ItemClassification.filler),
    LocationName.gallery_damsel[17]: SlayThePrincessItemData(offset + memories + 1217, ItemClassification.filler),
    LocationName.gallery_damsel[18]: SlayThePrincessItemData(offset + memories + 1218, ItemClassification.filler),
    LocationName.gallery_damsel[19]: SlayThePrincessItemData(offset + memories + 1219, ItemClassification.filler),
    LocationName.gallery_damsel[20]: SlayThePrincessItemData(offset + memories + 1220, ItemClassification.filler),

    LocationName.gallery_needle[1]: SlayThePrincessItemData(offset + memories + 1301, ItemClassification.filler),
    LocationName.gallery_needle[2]: SlayThePrincessItemData(offset + memories + 1302, ItemClassification.filler),
    LocationName.gallery_needle[3]: SlayThePrincessItemData(offset + memories + 1303, ItemClassification.filler),
    LocationName.gallery_needle[4]: SlayThePrincessItemData(offset + memories + 1304, ItemClassification.filler),
    LocationName.gallery_needle[5]: SlayThePrincessItemData(offset + memories + 1305, ItemClassification.filler),
    LocationName.gallery_needle[6]: SlayThePrincessItemData(offset + memories + 1306, ItemClassification.filler),
    LocationName.gallery_needle[7]: SlayThePrincessItemData(offset + memories + 1307, ItemClassification.filler),
    LocationName.gallery_needle[8]: SlayThePrincessItemData(offset + memories + 1308, ItemClassification.filler),
    LocationName.gallery_needle[9]: SlayThePrincessItemData(offset + memories + 1309, ItemClassification.filler),
    LocationName.gallery_needle[10]: SlayThePrincessItemData(offset + memories + 1310, ItemClassification.filler),
    LocationName.gallery_needle[11]: SlayThePrincessItemData(offset + memories + 1311, ItemClassification.filler),
    LocationName.gallery_needle[12]: SlayThePrincessItemData(offset + memories + 1312, ItemClassification.filler),
    LocationName.gallery_needle[13]: SlayThePrincessItemData(offset + memories + 1313, ItemClassification.filler),
    LocationName.gallery_needle[14]: SlayThePrincessItemData(offset + memories + 1314, ItemClassification.filler),
    LocationName.gallery_needle[15]: SlayThePrincessItemData(offset + memories + 1315, ItemClassification.filler),
    LocationName.gallery_needle[16]: SlayThePrincessItemData(offset + memories + 1316, ItemClassification.filler),
    LocationName.gallery_needle[17]: SlayThePrincessItemData(offset + memories + 1317, ItemClassification.filler),
    LocationName.gallery_needle[18]: SlayThePrincessItemData(offset + memories + 1318, ItemClassification.filler),
    LocationName.gallery_needle[19]: SlayThePrincessItemData(offset + memories + 1319, ItemClassification.filler),
    LocationName.gallery_needle[20]: SlayThePrincessItemData(offset + memories + 1320, ItemClassification.filler),

    LocationName.gallery_fury[1]: SlayThePrincessItemData(offset + memories + 1401, ItemClassification.filler),
    LocationName.gallery_fury[2]: SlayThePrincessItemData(offset + memories + 1402, ItemClassification.filler),
    LocationName.gallery_fury[3]: SlayThePrincessItemData(offset + memories + 1403, ItemClassification.filler),
    LocationName.gallery_fury[4]: SlayThePrincessItemData(offset + memories + 1404, ItemClassification.filler),
    LocationName.gallery_fury[5]: SlayThePrincessItemData(offset + memories + 1405, ItemClassification.filler),
    LocationName.gallery_fury[6]: SlayThePrincessItemData(offset + memories + 1406, ItemClassification.filler),
    LocationName.gallery_fury[7]: SlayThePrincessItemData(offset + memories + 1407, ItemClassification.filler),
    LocationName.gallery_fury[8]: SlayThePrincessItemData(offset + memories + 1408, ItemClassification.filler),
    LocationName.gallery_fury[9]: SlayThePrincessItemData(offset + memories + 1409, ItemClassification.filler),
    LocationName.gallery_fury[10]: SlayThePrincessItemData(offset + memories + 1410, ItemClassification.filler),
    LocationName.gallery_fury[11]: SlayThePrincessItemData(offset + memories + 1411, ItemClassification.filler),
    LocationName.gallery_fury[12]: SlayThePrincessItemData(offset + memories + 1412, ItemClassification.filler),
    LocationName.gallery_fury[13]: SlayThePrincessItemData(offset + memories + 1413, ItemClassification.filler),
    LocationName.gallery_fury[14]: SlayThePrincessItemData(offset + memories + 1414, ItemClassification.filler),
    LocationName.gallery_fury[15]: SlayThePrincessItemData(offset + memories + 1415, ItemClassification.filler),
    LocationName.gallery_fury[16]: SlayThePrincessItemData(offset + memories + 1416, ItemClassification.filler),
    LocationName.gallery_fury[17]: SlayThePrincessItemData(offset + memories + 1417, ItemClassification.filler),
    LocationName.gallery_fury[18]: SlayThePrincessItemData(offset + memories + 1418, ItemClassification.filler),
    LocationName.gallery_fury[19]: SlayThePrincessItemData(offset + memories + 1419, ItemClassification.filler),
    LocationName.gallery_fury[20]: SlayThePrincessItemData(offset + memories + 1420, ItemClassification.filler),

    LocationName.gallery_apotheosis[1]: SlayThePrincessItemData(offset + memories + 1501, ItemClassification.filler),
    LocationName.gallery_apotheosis[2]: SlayThePrincessItemData(offset + memories + 1502, ItemClassification.filler),
    LocationName.gallery_apotheosis[3]: SlayThePrincessItemData(offset + memories + 1503, ItemClassification.filler),
    LocationName.gallery_apotheosis[4]: SlayThePrincessItemData(offset + memories + 1504, ItemClassification.filler),
    LocationName.gallery_apotheosis[5]: SlayThePrincessItemData(offset + memories + 1505, ItemClassification.filler),
    LocationName.gallery_apotheosis[6]: SlayThePrincessItemData(offset + memories + 1506, ItemClassification.filler),
    LocationName.gallery_apotheosis[7]: SlayThePrincessItemData(offset + memories + 1507, ItemClassification.filler),
    LocationName.gallery_apotheosis[8]: SlayThePrincessItemData(offset + memories + 1508, ItemClassification.filler),
    LocationName.gallery_apotheosis[9]: SlayThePrincessItemData(offset + memories + 1509, ItemClassification.filler),
    LocationName.gallery_apotheosis[10]: SlayThePrincessItemData(offset + memories + 1510, ItemClassification.filler),
    LocationName.gallery_apotheosis[11]: SlayThePrincessItemData(offset + memories + 1511, ItemClassification.filler),
    LocationName.gallery_apotheosis[12]: SlayThePrincessItemData(offset + memories + 1512, ItemClassification.filler),
    LocationName.gallery_apotheosis[13]: SlayThePrincessItemData(offset + memories + 1513, ItemClassification.filler),
    LocationName.gallery_apotheosis[14]: SlayThePrincessItemData(offset + memories + 1514, ItemClassification.filler),
    LocationName.gallery_apotheosis[15]: SlayThePrincessItemData(offset + memories + 1515, ItemClassification.filler),
    LocationName.gallery_apotheosis[16]: SlayThePrincessItemData(offset + memories + 1516, ItemClassification.filler),
    LocationName.gallery_apotheosis[17]: SlayThePrincessItemData(offset + memories + 1517, ItemClassification.filler),
    LocationName.gallery_apotheosis[18]: SlayThePrincessItemData(offset + memories + 1518, ItemClassification.filler),
    LocationName.gallery_apotheosis[19]: SlayThePrincessItemData(offset + memories + 1519, ItemClassification.filler),
    LocationName.gallery_apotheosis[20]: SlayThePrincessItemData(offset + memories + 1520, ItemClassification.filler),

    LocationName.gallery_dragon[1]: SlayThePrincessItemData(offset + memories + 1601, ItemClassification.filler),
    LocationName.gallery_dragon[2]: SlayThePrincessItemData(offset + memories + 1602, ItemClassification.filler),
    LocationName.gallery_dragon[3]: SlayThePrincessItemData(offset + memories + 1603, ItemClassification.filler),
    LocationName.gallery_dragon[4]: SlayThePrincessItemData(offset + memories + 1604, ItemClassification.filler),
    LocationName.gallery_dragon[5]: SlayThePrincessItemData(offset + memories + 1605, ItemClassification.filler),
    LocationName.gallery_dragon[6]: SlayThePrincessItemData(offset + memories + 1606, ItemClassification.filler),
    LocationName.gallery_dragon[7]: SlayThePrincessItemData(offset + memories + 1607, ItemClassification.filler),
    LocationName.gallery_dragon[8]: SlayThePrincessItemData(offset + memories + 1608, ItemClassification.filler),
    LocationName.gallery_dragon[9]: SlayThePrincessItemData(offset + memories + 1609, ItemClassification.filler),
    LocationName.gallery_dragon[10]: SlayThePrincessItemData(offset + memories + 1610, ItemClassification.filler),
    LocationName.gallery_dragon[11]: SlayThePrincessItemData(offset + memories + 1611, ItemClassification.filler),
    LocationName.gallery_dragon[12]: SlayThePrincessItemData(offset + memories + 1612, ItemClassification.filler),
    LocationName.gallery_dragon[13]: SlayThePrincessItemData(offset + memories + 1613, ItemClassification.filler),
    LocationName.gallery_dragon[14]: SlayThePrincessItemData(offset + memories + 1614, ItemClassification.filler),
    LocationName.gallery_dragon[15]: SlayThePrincessItemData(offset + memories + 1615, ItemClassification.filler),
    LocationName.gallery_dragon[16]: SlayThePrincessItemData(offset + memories + 1616, ItemClassification.filler),
    LocationName.gallery_dragon[17]: SlayThePrincessItemData(offset + memories + 1617, ItemClassification.filler),
    LocationName.gallery_dragon[18]: SlayThePrincessItemData(offset + memories + 1618, ItemClassification.filler),
    LocationName.gallery_dragon[19]: SlayThePrincessItemData(offset + memories + 1619, ItemClassification.filler),
    LocationName.gallery_dragon[20]: SlayThePrincessItemData(offset + memories + 1620, ItemClassification.filler),

    LocationName.gallery_wraith[1]: SlayThePrincessItemData(offset + memories + 1701, ItemClassification.filler),
    LocationName.gallery_wraith[2]: SlayThePrincessItemData(offset + memories + 1702, ItemClassification.filler),
    LocationName.gallery_wraith[3]: SlayThePrincessItemData(offset + memories + 1703, ItemClassification.filler),
    LocationName.gallery_wraith[4]: SlayThePrincessItemData(offset + memories + 1704, ItemClassification.filler),
    LocationName.gallery_wraith[5]: SlayThePrincessItemData(offset + memories + 1705, ItemClassification.filler),
    LocationName.gallery_wraith[6]: SlayThePrincessItemData(offset + memories + 1706, ItemClassification.filler),
    LocationName.gallery_wraith[7]: SlayThePrincessItemData(offset + memories + 1707, ItemClassification.filler),
    LocationName.gallery_wraith[8]: SlayThePrincessItemData(offset + memories + 1708, ItemClassification.filler),
    LocationName.gallery_wraith[9]: SlayThePrincessItemData(offset + memories + 1709, ItemClassification.filler),
    LocationName.gallery_wraith[10]: SlayThePrincessItemData(offset + memories + 1710, ItemClassification.filler),
    LocationName.gallery_wraith[11]: SlayThePrincessItemData(offset + memories + 1711, ItemClassification.filler),

    LocationName.gallery_clarity[1]: SlayThePrincessItemData(offset + memories + 1801, ItemClassification.filler),
    LocationName.gallery_clarity[2]: SlayThePrincessItemData(offset + memories + 1802, ItemClassification.filler),
    LocationName.gallery_clarity[3]: SlayThePrincessItemData(offset + memories + 1803, ItemClassification.filler),
    LocationName.gallery_clarity[4]: SlayThePrincessItemData(offset + memories + 1804, ItemClassification.filler),
    LocationName.gallery_clarity[5]: SlayThePrincessItemData(offset + memories + 1805, ItemClassification.filler),
    LocationName.gallery_clarity[6]: SlayThePrincessItemData(offset + memories + 1806, ItemClassification.filler),
    LocationName.gallery_clarity[7]: SlayThePrincessItemData(offset + memories + 1807, ItemClassification.filler),
    LocationName.gallery_clarity[8]: SlayThePrincessItemData(offset + memories + 1808, ItemClassification.filler),
    LocationName.gallery_clarity[9]: SlayThePrincessItemData(offset + memories + 1809, ItemClassification.filler),
    LocationName.gallery_clarity[10]: SlayThePrincessItemData(offset + memories + 1810, ItemClassification.filler),
    LocationName.gallery_clarity[11]: SlayThePrincessItemData(offset + memories + 1811, ItemClassification.filler),
    LocationName.gallery_clarity[12]: SlayThePrincessItemData(offset + memories + 1812, ItemClassification.filler),
    LocationName.gallery_clarity[13]: SlayThePrincessItemData(offset + memories + 1813, ItemClassification.filler),
    LocationName.gallery_clarity[14]: SlayThePrincessItemData(offset + memories + 1814, ItemClassification.filler),

    LocationName.gallery_den[1]: SlayThePrincessItemData(offset + memories + 1901, ItemClassification.filler),
    LocationName.gallery_den[2]: SlayThePrincessItemData(offset + memories + 1902, ItemClassification.filler),
    LocationName.gallery_den[3]: SlayThePrincessItemData(offset + memories + 1903, ItemClassification.filler),
    LocationName.gallery_den[4]: SlayThePrincessItemData(offset + memories + 1904, ItemClassification.filler),
    LocationName.gallery_den[5]: SlayThePrincessItemData(offset + memories + 1905, ItemClassification.filler),
    LocationName.gallery_den[6]: SlayThePrincessItemData(offset + memories + 1906, ItemClassification.filler),
    LocationName.gallery_den[7]: SlayThePrincessItemData(offset + memories + 1907, ItemClassification.filler),
    LocationName.gallery_den[8]: SlayThePrincessItemData(offset + memories + 1908, ItemClassification.filler),
    LocationName.gallery_den[9]: SlayThePrincessItemData(offset + memories + 1909, ItemClassification.filler),
    LocationName.gallery_den[10]: SlayThePrincessItemData(offset + memories + 1910, ItemClassification.filler),
    LocationName.gallery_den[11]: SlayThePrincessItemData(offset + memories + 1911, ItemClassification.filler),
    LocationName.gallery_den[12]: SlayThePrincessItemData(offset + memories + 1912, ItemClassification.filler),
    LocationName.gallery_den[13]: SlayThePrincessItemData(offset + memories + 1913, ItemClassification.filler),
    LocationName.gallery_den[14]: SlayThePrincessItemData(offset + memories + 1914, ItemClassification.filler),
    LocationName.gallery_den[15]: SlayThePrincessItemData(offset + memories + 1915, ItemClassification.filler),
    LocationName.gallery_den[16]: SlayThePrincessItemData(offset + memories + 1916, ItemClassification.filler),
    LocationName.gallery_den[17]: SlayThePrincessItemData(offset + memories + 1917, ItemClassification.filler),
    LocationName.gallery_den[18]: SlayThePrincessItemData(offset + memories + 1918, ItemClassification.filler),
    LocationName.gallery_den[19]: SlayThePrincessItemData(offset + memories + 1919, ItemClassification.filler),
    LocationName.gallery_den[20]: SlayThePrincessItemData(offset + memories + 1920, ItemClassification.filler),

    LocationName.gallery_wild[1]: SlayThePrincessItemData(offset + memories + 2001, ItemClassification.filler),
    LocationName.gallery_wild[2]: SlayThePrincessItemData(offset + memories + 2002, ItemClassification.filler),
    LocationName.gallery_wild[3]: SlayThePrincessItemData(offset + memories + 2003, ItemClassification.filler),
    LocationName.gallery_wild[4]: SlayThePrincessItemData(offset + memories + 2004, ItemClassification.filler),
    LocationName.gallery_wild[5]: SlayThePrincessItemData(offset + memories + 2005, ItemClassification.filler),
    LocationName.gallery_wild[6]: SlayThePrincessItemData(offset + memories + 2006, ItemClassification.filler),
    LocationName.gallery_wild[7]: SlayThePrincessItemData(offset + memories + 2007, ItemClassification.filler),
    LocationName.gallery_wild[8]: SlayThePrincessItemData(offset + memories + 2008, ItemClassification.filler),
    LocationName.gallery_wild[9]: SlayThePrincessItemData(offset + memories + 2009, ItemClassification.filler),
    LocationName.gallery_wild[10]: SlayThePrincessItemData(offset + memories + 2010, ItemClassification.filler),
    LocationName.gallery_wild[11]: SlayThePrincessItemData(offset + memories + 2011, ItemClassification.filler),
    LocationName.gallery_wild[12]: SlayThePrincessItemData(offset + memories + 2012, ItemClassification.filler),

    LocationName.gallery_thorn[1]: SlayThePrincessItemData(offset + memories + 2101, ItemClassification.filler),
    LocationName.gallery_thorn[2]: SlayThePrincessItemData(offset + memories + 2102, ItemClassification.filler),
    LocationName.gallery_thorn[3]: SlayThePrincessItemData(offset + memories + 2103, ItemClassification.filler),
    LocationName.gallery_thorn[4]: SlayThePrincessItemData(offset + memories + 2104, ItemClassification.filler),
    LocationName.gallery_thorn[5]: SlayThePrincessItemData(offset + memories + 2105, ItemClassification.filler),
    LocationName.gallery_thorn[6]: SlayThePrincessItemData(offset + memories + 2106, ItemClassification.filler),
    LocationName.gallery_thorn[7]: SlayThePrincessItemData(offset + memories + 2107, ItemClassification.filler),
    LocationName.gallery_thorn[8]: SlayThePrincessItemData(offset + memories + 2108, ItemClassification.filler),
    LocationName.gallery_thorn[9]: SlayThePrincessItemData(offset + memories + 2109, ItemClassification.filler),
    LocationName.gallery_thorn[10]: SlayThePrincessItemData(offset + memories + 2110, ItemClassification.filler),
    LocationName.gallery_thorn[11]: SlayThePrincessItemData(offset + memories + 2111, ItemClassification.filler),
    LocationName.gallery_thorn[12]: SlayThePrincessItemData(offset + memories + 2112, ItemClassification.filler),
    LocationName.gallery_thorn[13]: SlayThePrincessItemData(offset + memories + 2113, ItemClassification.filler),
    LocationName.gallery_thorn[14]: SlayThePrincessItemData(offset + memories + 2114, ItemClassification.filler),
    LocationName.gallery_thorn[15]: SlayThePrincessItemData(offset + memories + 2115, ItemClassification.filler),
    LocationName.gallery_thorn[16]: SlayThePrincessItemData(offset + memories + 2116, ItemClassification.filler),
    LocationName.gallery_thorn[17]: SlayThePrincessItemData(offset + memories + 2117, ItemClassification.filler),
    LocationName.gallery_thorn[18]: SlayThePrincessItemData(offset + memories + 2118, ItemClassification.filler),
    LocationName.gallery_thorn[19]: SlayThePrincessItemData(offset + memories + 2119, ItemClassification.filler),

    LocationName.gallery_cage[1]: SlayThePrincessItemData(offset + memories + 2201, ItemClassification.filler),
    LocationName.gallery_cage[2]: SlayThePrincessItemData(offset + memories + 2202, ItemClassification.filler),
    LocationName.gallery_cage[3]: SlayThePrincessItemData(offset + memories + 2203, ItemClassification.filler),
    LocationName.gallery_cage[4]: SlayThePrincessItemData(offset + memories + 2204, ItemClassification.filler),
    LocationName.gallery_cage[5]: SlayThePrincessItemData(offset + memories + 2205, ItemClassification.filler),
    LocationName.gallery_cage[6]: SlayThePrincessItemData(offset + memories + 2206, ItemClassification.filler),
    LocationName.gallery_cage[7]: SlayThePrincessItemData(offset + memories + 2207, ItemClassification.filler),
    LocationName.gallery_cage[8]: SlayThePrincessItemData(offset + memories + 2208, ItemClassification.filler),
    LocationName.gallery_cage[9]: SlayThePrincessItemData(offset + memories + 2209, ItemClassification.filler),
    LocationName.gallery_cage[10]: SlayThePrincessItemData(offset + memories + 2210, ItemClassification.filler),
    LocationName.gallery_cage[11]: SlayThePrincessItemData(offset + memories + 2211, ItemClassification.filler),
    LocationName.gallery_cage[12]: SlayThePrincessItemData(offset + memories + 2212, ItemClassification.filler),
    LocationName.gallery_cage[13]: SlayThePrincessItemData(offset + memories + 2213, ItemClassification.filler),
    LocationName.gallery_cage[14]: SlayThePrincessItemData(offset + memories + 2214, ItemClassification.filler),
    LocationName.gallery_cage[15]: SlayThePrincessItemData(offset + memories + 2215, ItemClassification.filler),
    LocationName.gallery_cage[16]: SlayThePrincessItemData(offset + memories + 2216, ItemClassification.filler),
    LocationName.gallery_cage[17]: SlayThePrincessItemData(offset + memories + 2217, ItemClassification.filler),
    LocationName.gallery_cage[18]: SlayThePrincessItemData(offset + memories + 2218, ItemClassification.filler),
    LocationName.gallery_cage[19]: SlayThePrincessItemData(offset + memories + 2219, ItemClassification.filler),
    LocationName.gallery_cage[20]: SlayThePrincessItemData(offset + memories + 2220, ItemClassification.filler),

    LocationName.gallery_grey[1]: SlayThePrincessItemData(offset + memories + 2301, ItemClassification.filler),
    LocationName.gallery_grey[2]: SlayThePrincessItemData(offset + memories + 2302, ItemClassification.filler),
    LocationName.gallery_grey[3]: SlayThePrincessItemData(offset + memories + 2303, ItemClassification.filler),
    LocationName.gallery_grey[4]: SlayThePrincessItemData(offset + memories + 2304, ItemClassification.filler),
    LocationName.gallery_grey[5]: SlayThePrincessItemData(offset + memories + 2305, ItemClassification.filler),
    LocationName.gallery_grey[6]: SlayThePrincessItemData(offset + memories + 2306, ItemClassification.filler),
    LocationName.gallery_grey[7]: SlayThePrincessItemData(offset + memories + 2307, ItemClassification.filler),
    LocationName.gallery_grey[8]: SlayThePrincessItemData(offset + memories + 2308, ItemClassification.filler),
    LocationName.gallery_grey[9]: SlayThePrincessItemData(offset + memories + 2309, ItemClassification.filler),
    LocationName.gallery_grey[10]: SlayThePrincessItemData(offset + memories + 2310, ItemClassification.filler),
    LocationName.gallery_grey[11]: SlayThePrincessItemData(offset + memories + 2311, ItemClassification.filler),
    LocationName.gallery_grey[12]: SlayThePrincessItemData(offset + memories + 2312, ItemClassification.filler),
    LocationName.gallery_grey[13]: SlayThePrincessItemData(offset + memories + 2313, ItemClassification.filler),
    LocationName.gallery_grey[14]: SlayThePrincessItemData(offset + memories + 2314, ItemClassification.filler),
    LocationName.gallery_grey[15]: SlayThePrincessItemData(offset + memories + 2315, ItemClassification.filler),
    LocationName.gallery_grey[16]: SlayThePrincessItemData(offset + memories + 2316, ItemClassification.filler),
    LocationName.gallery_grey[17]: SlayThePrincessItemData(offset + memories + 2317, ItemClassification.filler),
    LocationName.gallery_grey[18]: SlayThePrincessItemData(offset + memories + 2318, ItemClassification.filler),
    LocationName.gallery_grey[19]: SlayThePrincessItemData(offset + memories + 2319, ItemClassification.filler),
    LocationName.gallery_grey[20]: SlayThePrincessItemData(offset + memories + 2320, ItemClassification.filler),

    LocationName.gallery_happily[1]: SlayThePrincessItemData(offset + memories + 2401, ItemClassification.filler),
    LocationName.gallery_happily[2]: SlayThePrincessItemData(offset + memories + 2402, ItemClassification.filler),
    LocationName.gallery_happily[3]: SlayThePrincessItemData(offset + memories + 2403, ItemClassification.filler),
    LocationName.gallery_happily[4]: SlayThePrincessItemData(offset + memories + 2404, ItemClassification.filler),
    LocationName.gallery_happily[5]: SlayThePrincessItemData(offset + memories + 2405, ItemClassification.filler),
    LocationName.gallery_happily[6]: SlayThePrincessItemData(offset + memories + 2406, ItemClassification.filler),
    LocationName.gallery_happily[7]: SlayThePrincessItemData(offset + memories + 2407, ItemClassification.filler),
    LocationName.gallery_happily[8]: SlayThePrincessItemData(offset + memories + 2408, ItemClassification.filler),
    LocationName.gallery_happily[9]: SlayThePrincessItemData(offset + memories + 2409, ItemClassification.filler),
    LocationName.gallery_happily[10]: SlayThePrincessItemData(offset + memories + 2410, ItemClassification.filler),
    LocationName.gallery_happily[11]: SlayThePrincessItemData(offset + memories + 2411, ItemClassification.filler),
    LocationName.gallery_happily[12]: SlayThePrincessItemData(offset + memories + 2412, ItemClassification.filler),
    LocationName.gallery_happily[13]: SlayThePrincessItemData(offset + memories + 2413, ItemClassification.filler),
    LocationName.gallery_happily[14]: SlayThePrincessItemData(offset + memories + 2414, ItemClassification.filler),
    LocationName.gallery_happily[15]: SlayThePrincessItemData(offset + memories + 2415, ItemClassification.filler),
    LocationName.gallery_happily[16]: SlayThePrincessItemData(offset + memories + 2416, ItemClassification.filler),
    LocationName.gallery_happily[17]: SlayThePrincessItemData(offset + memories + 2417, ItemClassification.filler),
    LocationName.gallery_happily[18]: SlayThePrincessItemData(offset + memories + 2418, ItemClassification.filler),
    LocationName.gallery_happily[19]: SlayThePrincessItemData(offset + memories + 2419, ItemClassification.filler),
    LocationName.gallery_happily[20]: SlayThePrincessItemData(offset + memories + 2420, ItemClassification.filler),
}

item_data_table: Dict[str, SlayThePrincessItemData] = {**other_item_data_table,
                                                       **blade_item_data_table,
                                                       **blade_chapter_item_data_table,
                                                       **blade_princess_item_data_table,
                                                       **princess_item_data_table,
                                                       **voice_item_data_table,
                                                       **gallery_item_data_table}

item_table = {name: data.code for name, data in item_data_table.items() if data.code is not None}
